In [1]:
import pandas as pd

In [2]:
df_exams = pd.read_csv('StudentsPerformance.csv')

In [3]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# Adding a new column

## 1.1 Adding a new column with a scalar value

In [4]:
df_exams['language score'] = 70

In [5]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

## Adding a new column with an array

In [6]:
import numpy as np

In [9]:
language_score = np.arange(0,1000)

In [10]:
len(language_score)

1000

In [12]:
df_exams['language score'] = language_score

In [13]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [15]:
#create random interger numbers between 1 to 100
# min,max, size of the dataset to be set ,,, min is inclusive and max is exclusive
int_language_score = np.random.randint(1, 100, size = 1000)

In [16]:
df_exams['language score'] = int_language_score 
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,82
1,female,group C,some college,standard,completed,69,90,88,59
2,female,group B,master's degree,standard,none,90,95,93,38
3,male,group A,associate's degree,free/reduced,none,47,57,44,49
4,male,group C,some college,standard,none,76,78,75,14
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,14
996,male,group C,high school,free/reduced,none,62,55,55,21
997,female,group C,high school,free/reduced,completed,59,71,65,74
998,female,group D,some college,standard,completed,68,78,77,46
999,female,group D,some college,free/reduced,none,77,86,86,77

In [17]:
# create random float numbers between 1 to 100
np.random.uniform(1,100,size = 100)

array([50.70299661, 76.88534881, 78.44785417, 64.16844998, 82.1086955 ,
       86.68291432, 46.98124232, 40.12211139, 34.54957121, 15.70027479,
       59.72303896, 66.07905288, 42.05633578, 73.53716453, 26.47843793,
       51.89739703, 67.1825374 , 56.51561924, 82.52614432, 11.54351326,
       73.24686468, 95.9612913 ,  4.87041184, 99.50310088, 57.51350481,
       91.75203723, 55.31451912, 85.003451  , 51.17161397, 36.85589208,
       94.44028589, 85.00383141, 42.67168079, 47.64777361, 16.06468407,
       78.40450109, 55.88162784, 35.83988592, 46.44775615, 60.64235534,
       43.70811961, 21.29431746, 70.95575463, 23.62592209, 10.34728757,
       38.68574408, 15.31571917,  9.66585672, 37.83239848, 32.08973294,
       31.60111101, 26.82886041, 47.97064596, 24.88095308, 68.26946594,
       82.77529041, 68.61975678, 82.14423792, 91.29607366, 93.80881335,
       25.47662788, 13.70953521, 87.76611636, 70.80295374,  6.22846437,
       38.08661096, 52.12600735, 25.90361021, 58.03341287, 78.88566166,
       73.33896984,  6.70814041, 45.73241286, 62.9935225 , 13.65616158,
       38.41856977, 95.36974839, 87.51724724, 20.58306591, 52.33548199,
       84.22953119, 44.6390664 , 30.14194429, 14.37774445, 34.03183405,
       80.37590399, 63.7005528 , 22.5289057 , 48.83089543, 54.01222897,
       25.66350207, 61.16616595, 95.12222283, 53.55498368, 61.45168859,
       82.75949565, 30.55249884, 33.87669497,  9.69945351, 34.92569632])

# Add new column using the assign() and insert()

### 1.1 assign()
when to use assign?
- Add multiple columns in a single line of code
- when you need to overwrite the values of an existing columns
- it returns a new object(a copy) with the original columns in addition to new ones

In [18]:
import numpy as np

In [19]:
# create random numbers for our new score columns
score1 = np.random.randint(1,100,size = 1000)
score2 = np.random.randint(1,100,size = 1000)

In [21]:
# create a series using the random numbers
series1 = pd.Series(score1, index=np.arange(0, 1000))
series2 = pd.Series(score1, index=np.arange(0, 1000))

In [24]:
# using the assign() to add multiple columns
df_exams = df_exams.assign(score1=series1, score2=series2)

In [25]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,82,54,54
1,female,group C,some college,standard,completed,69,90,88,59,32,32
2,female,group B,master's degree,standard,none,90,95,93,38,88,88
3,male,group A,associate's degree,free/reduced,none,47,57,44,49,79,79
4,male,group C,some college,standard,none,76,78,75,14,69,69
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,14,99,99
996,male,group C,high school,free/reduced,none,62,55,55,21,10,10
997,female,group C,high school,free/reduced,completed,59,71,65,74,18,18
998,female,group D,some college,standard,completed,68,78,77,46,38,38
999,female,group D,some college,free/reduced,none,77,86,86,77,66,66

## 1.2 insert()
- inserts a new column at a specific position or index

In [30]:
# using index() to add a column at a specific position
df_exams.insert(1,'test',series1)

ValueError: cannot insert test, already exists

In [31]:
# show dataFrame
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,54,group B,bachelor's degree,standard,none,72,72,74,82,54,54
1,female,32,group C,some college,standard,completed,69,90,88,59,32,32
2,female,88,group B,master's degree,standard,none,90,95,93,38,88,88
3,male,79,group A,associate's degree,free/reduced,none,47,57,44,49,79,79
4,male,69,group C,some college,standard,none,76,78,75,14,69,69
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,99,group E,master's degree,standard,completed,88,99,95,14,99,99
996,male,10,group C,high school,free/reduced,none,62,55,55,21,10,10
997,female,18,group C,high school,free/reduced,completed,59,71,65,74,18,18
998,female,38,group D,some college,standard,completed,68,78,77,46,38,38
999,female,66,group D,some college,free/reduced,none,77,86,86,77,66,66