In [2]:
import pandas as pd

In [3]:
df_exams = pd.read_csv('StudentsPerformance.csv')

In [4]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# Math Operations

## 1.1 Operations in columns

In [4]:
# select a column and calculate total sum
df_exams['math score'].sum()

np.int64(66089)

In [5]:
# count, mean, std, max, and min
df_exams['math score'].count()

np.int64(1000)

In [6]:
df_exams['math score'].mean()

np.float64(66.089)

In [7]:
df_exams['math score'].std()

np.float64(15.16308009600945)

In [8]:
df_exams['math score'].min()

np.int64(0)

In [9]:
df_exams['math score'].max()

np.int64(100)

### easier calculation with .describe()

In [10]:
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

## 1.2 operations in row

In [5]:
# calculate the sum in a row
df_exams['math score']+df_exams['reading score']+df_exams['writing score']

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [6]:
# calculating the average
df_exams['average'] = (df_exams['math score']+df_exams['reading score']+df_exams['writing score'])/3

In [8]:
df_exams.round(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
0,female,group B,bachelor's degree,standard,none,72,72,74,72.67
1,female,group C,some college,standard,completed,69,90,88,82.33
2,female,group B,master's degree,standard,none,90,95,93,92.67
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.33
4,male,group C,some college,standard,none,76,78,75,76.33
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.00
996,male,group C,high school,free/reduced,none,62,55,55,57.33
997,female,group C,high school,free/reduced,completed,59,71,65,65.00
998,female,group D,some college,standard,completed,68,78,77,74.33
999,female,group D,some college,free/reduced,none,77,86,86,83.00

# 1 value count

In [11]:
#counting gender elements


#len function
len(df_exams)
#.count() method
df_exams['gender'].count()

np.int64(1000)

In [12]:
# calculating gender element by category
df_exams['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [13]:
df_exams['gender'].value_counts(normalize=True)

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

In [14]:
df_exams['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [16]:
# if we want percentage use normalize
df_exams['parental level of education'].value_counts(normalize=True).round(2)

parental level of education
some college          0.23
associate's degree    0.22
high school           0.20
some high school      0.18
bachelor's degree     0.12
master's degree       0.06
Name: proportion, dtype: float64

# Sort the dataframe

In [17]:
# sort by one column 
# by default ascending
df_exams.sort_values(by='math score')

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000
980,female,group B,high school,free/reduced,none,8,24,23,18.333333
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000
787,female,group B,some college,standard,none,19,38,32,29.666667
145,female,group C,some college,free/reduced,none,22,39,33,31.333333
...,...,...,...,...,...,...,...,...,...
962,female,group E,associate's degree,standard,none,100,100,100,100.000000
625,male,group D,some college,standard,completed,100,97,99,98.666667
916,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000
451,female,group E,some college,standard,none,100,92,97,96.333333

In [18]:
# sort in descending by one column
df_exams.sort_values('math score',ascending = False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
962,female,group E,associate's degree,standard,none,100,100,100,100.000000
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000
149,male,group E,associate's degree,free/reduced,completed,100,100,93,97.666667
625,male,group D,some college,standard,completed,100,97,99,98.666667
916,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000
...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,31.333333
787,female,group B,some college,standard,none,19,38,32,29.666667
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000
980,female,group B,high school,free/reduced,none,8,24,23,18.333333
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000

In [19]:
# sort descending my multiple column
df_exams.sort_values(['math score','reading score'],ascending = False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
149,male,group E,associate's degree,free/reduced,completed,100,100,93,97.666667
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000
916,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000
962,female,group E,associate's degree,standard,none,100,100,100,100.000000
625,male,group D,some college,standard,completed,100,97,99,98.666667
...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,31.333333
787,female,group B,some college,standard,none,19,38,32,29.666667
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000
980,female,group B,high school,free/reduced,none,8,24,23,18.333333
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000

In [20]:
# sort descending my multiple column and update dataframe
df_exams.sort_values(['math score','reading score'],ascending = False,inplace = True)

In [21]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
149,male,group E,associate's degree,free/reduced,completed,100,100,93,97.666667
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000
916,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000
962,female,group E,associate's degree,standard,none,100,100,100,100.000000
625,male,group D,some college,standard,completed,100,97,99,98.666667
...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,31.333333
787,female,group B,some college,standard,none,19,38,32,29.666667
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000
980,female,group B,high school,free/reduced,none,8,24,23,18.333333
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000

In [22]:
# sort with text using descending a key function
# lambda return_obj : return_obj+operations
df_exams.sort_values('race/ethnicity',ascending=True,key= lambda col: col.str.lower())

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
741,female,group A,associate's degree,free/reduced,none,37,57,56,50.000000
151,male,group A,bachelor's degree,standard,none,77,67,68,70.666667
811,male,group A,high school,free/reduced,none,45,47,49,47.000000
112,male,group A,associate's degree,standard,none,54,53,47,51.333333
25,male,group A,master's degree,free/reduced,none,73,74,72,73.000000
...,...,...,...,...,...,...,...,...,...
751,male,group E,some college,standard,none,68,72,65,68.333333
915,female,group E,some college,standard,none,68,70,66,68.000000
592,male,group E,bachelor's degree,standard,none,68,68,64,66.666667
479,male,group E,associate's degree,standard,none,76,71,67,71.333333
517,female,group E,some college,standard,completed,66,74,73,71.000000

# The set_index() and sort_index() methods

# create index

In [23]:
import numpy as np
import random

In [24]:
# creating non repetitive values for the index
new_index = np.arange(0, 1000)

In [25]:
random.shuffle(new_index)

In [26]:
new_index

array([ 98, 403, 155, 273, 738, 623, 639, 243, 459, 906, 632, 860, 992,
       334, 166, 916, 588,  53, 789, 696, 326, 799, 163, 708, 910, 364,
       308, 209, 441, 954, 466, 368,  40, 832, 469, 631, 407, 674, 444,
       568,  58, 657, 555, 402, 957,  72, 240, 189, 500, 926, 470, 250,
       443, 265, 332, 905, 331, 953, 354, 932, 781, 898, 264, 800, 392,
       877, 935, 422, 539, 229, 845, 160, 722, 687, 536, 206, 797, 352,
       246, 711, 730,  93, 399, 410, 777, 463, 812, 651, 451, 121, 434,
       168,  15, 716, 900, 333, 755, 218, 413, 836, 468, 371, 782, 108,
       865, 592, 537, 591, 680, 918, 693, 499, 107, 725,  46, 878, 939,
       477, 792, 712, 843, 946, 220, 547, 958, 909, 416, 179, 968, 101,
       643, 780, 272,   6,  64, 381, 767, 482, 986, 317, 868, 570, 644,
       484, 301, 516, 534, 503, 635, 774, 221, 737, 391, 312, 330, 808,
       569, 367, 262, 614, 899, 931, 236, 509,  41, 991, 806,  95, 733,
        20,  84,  77, 604, 270, 605, 528, 285, 694, 754, 951, 120, 514,
       546, 998, 985, 619, 409, 310, 975, 825, 949, 196,  63, 745, 185,
       157, 924, 251, 104, 661, 840, 127, 744, 315, 676, 691, 197,  85,
       576, 213, 496, 474, 952, 579, 880, 757, 316, 201, 950, 366, 300,
       923, 199, 322, 876,  45, 321, 527, 893, 343,  49, 177, 223, 558,
       645, 225,  99, 191, 842, 274,  13, 940, 346, 679, 813, 405, 787,
       435, 320, 697, 158, 489, 833, 129, 305, 967, 665, 349, 943, 400,
       103, 430,  25, 564, 642, 379,   5, 559, 686, 706, 143, 907, 329,
       760, 914, 275, 960,  10, 822, 695, 741, 464, 169,  87,  91, 779,
        38, 815,  71, 689, 481, 902, 929, 584, 504, 386, 508, 417, 395,
       685,  73, 452, 987, 235, 715, 529, 115, 709,  50, 174, 269, 377,
       406, 888, 749, 847, 748,   2, 887,  26, 471, 625, 850, 734, 934,
       575,  62, 171, 152, 436, 145,  82,  67, 566, 170, 335,  55, 699,
       394, 187, 912,   0, 433, 298, 612, 972, 763, 478, 105, 132,  37,
       723, 186, 658, 327, 761, 936, 624, 703, 156, 997, 450, 259, 585,
       593, 525, 268, 807, 999, 415,  32, 242, 974, 990, 567, 215, 212,
       118, 291, 427, 798, 675, 287, 571, 678, 309, 404, 794, 280, 600,
       122, 607, 245, 494, 139, 608, 456, 942, 544, 339, 855, 455,  42,
       521, 306, 340, 545, 401, 573, 440, 412, 211, 672, 420, 161, 530,
       378, 655, 594, 556, 837, 257, 517, 753, 948,  39,  34, 351, 816,
       114, 184, 369,  57, 581, 167, 204, 980, 917, 603, 955, 788, 159,
       307, 677, 385, 875, 532, 647, 227, 882,  36, 620, 483, 208, 501,
        70, 627, 232, 219, 109, 125, 790, 629, 859, 224, 778, 903,  60,
       131, 423,  88, 838, 814, 106, 380, 207, 598, 828, 618, 253, 357,
       324, 284, 582, 941, 671, 606, 580, 533, 226,  89, 851, 766, 561,
       258, 288,  21, 457, 577, 849, 751, 817, 690, 429, 491, 883, 192,
       277, 892, 183, 670, 811, 908, 182, 214, 137, 626, 994, 531,  12,
       421, 102, 945, 140, 239, 846, 150, 622, 649, 303, 803, 764, 256,
       654,  90, 492, 431, 844, 228, 437, 973, 397, 988,  74, 920, 724,
       540, 873,  94, 341,  80, 650, 507, 548, 428, 775, 830, 857, 389,
       947, 872, 638, 248, 735, 283, 597, 141, 966,  76, 164, 176, 554,
       485, 913,   8, 551, 302, 281, 360, 337, 925, 387, 977, 445, 732,
        16, 664, 522, 684, 823, 314, 194, 497, 130, 278, 762, 506,  31,
       493, 202, 721,  22, 418, 667, 662, 162, 467, 318, 238, 216,  79,
       795,  96, 313, 325, 465, 230, 683, 827, 511,  11, 290, 396, 728,
       393, 111, 292, 193, 710, 375, 921, 475, 786, 718, 743, 154, 458,
        78, 617, 538, 382, 864, 656, 831, 611, 438, 279, 487, 252, 901,
       854, 135,  54, 439, 746, 244, 365,  30,  61, 589, 633, 848, 641,
        81, 704, 147, 390, 824, 783, 110,  68, 222, 237, 707, 839, 714,
       144, 553, 596, 702,  29, 442, 630, 411, 323, 993, 100, 962, 961,
       874,  86, 286, 984, 768, 669, 336, 731, 981, 473, 682, 175, 535,
       432, 927, 345, 698, 796, 123, 267,  69, 769, 355, 461,  14, 637,
       681, 894, 148, 835, 784, 621, 295, 895, 982, 771, 117, 480, 583,
       663, 930, 398, 805, 505, 740,  27, 476, 700, 384, 241, 513, 793,
       374, 759, 866, 353, 217,   3,  28, 646, 338, 304, 879, 112, 862,
         1, 729, 867, 195, 543, 820, 810, 586, 613, 142, 653, 933, 510,
       255, 299, 802, 599, 448, 979, 347, 526, 928, 462, 861, 495,   4,
       297, 361, 350, 640, 550, 717, 460, 518, 342, 372, 376, 293,  43,
       424, 870, 668, 978, 490, 165, 881, 370, 660, 266, 601, 523, 133,
       628, 938,  19, 758, 719, 785, 886, 688, 673, 344, 363, 200, 801,
       919,  47, 590, 819, 826, 666, 126, 884, 727, 373, 419, 425, 574,
       294, 515, 713, 113, 263, 915, 890, 498, 944, 362, 426, 841, 134,
       896,  23, 512, 233, 970,  17, 180, 519, 615, 742, 562, 549, 563,
       965, 648, 520, 602, 383, 146, 296,  92, 231,  65, 138, 616,  48,
       829, 809, 963, 863, 328, 856, 408, 254,  59, 128, 995, 634, 834,
       124, 891,  83, 205, 261, 852, 904, 453, 119,  75, 414, 488, 151,
        52, 552, 359, 203, 116, 289, 486, 871,  18, 964, 772, 869, 756,
       750, 705, 853,  66, 889, 181, 172, 692, 388, 858, 776, 652, 595,
       247, 358, 726, 249, 447,  97, 282, 271, 210, 752, 736, 818, 188,
       234, 560, 821,   9, 922, 969, 989, 178, 609, 804, 198, 773, 937,
        24, 149, 578, 983, 572, 976, 897, 454, 319, 479, 541, 136, 720,
       770, 739, 449,  44, 356, 153, 791,  35, 636, 276, 542, 587, 911,
        56, 659, 173, 557, 971, 610, 348, 190, 524, 956,  51, 446, 260,
       996,  33, 959, 311, 885, 472, 747, 701, 565, 765,   7, 502])

In [28]:
# create a new column with new index
df_exams['new_index'] = new_index

In [29]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average,new_index
149,male,group E,associate's degree,free/reduced,completed,100,100,93,97.666667,98
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000,403
916,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000,155
962,female,group E,associate's degree,standard,none,100,100,100,100.000000,273
625,male,group D,some college,standard,completed,100,97,99,98.666667,738
...,...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,31.333333,701
787,female,group B,some college,standard,none,19,38,32,29.666667,565
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000,765
980,female,group B,high school,free/reduced,none,8,24,23,18.333333,7
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000,502

#  set index

In [31]:
# set new_index column as index
df_exams.set_index('new_index',inplace = True)

In [32]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
new_index,,,,,,,,,
98,male,group E,associate's degree,free/reduced,completed,100,100,93,97.666667
403,female,group E,bachelor's degree,standard,none,100,100,100,100.000000
155,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000
273,female,group E,associate's degree,standard,none,100,100,100,100.000000
738,male,group D,some college,standard,completed,100,97,99,98.666667
...,...,...,...,...,...,...,...,...,...
701,female,group C,some college,free/reduced,none,22,39,33,31.333333
565,female,group B,some college,standard,none,19,38,32,29.666667
765,female,group B,some high school,free/reduced,none,18,32,28,26.000000
7,female,group B,high school,free/reduced,none,8,24,23,18.333333
502,female,group C,some high school,free/reduced,none,0,17,10,9.000000

# Sort index

In [33]:
# sort dataframe by new index
df_exams.sort_index()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
new_index,,,,,,,,,
0,male,group E,some high school,free/reduced,completed,73,67,59,66.333333
1,female,group D,high school,standard,completed,56,68,74,66.000000
2,male,group D,high school,free/reduced,none,74,70,69,71.000000
3,male,group E,high school,free/reduced,completed,57,56,54,55.666667
4,male,group C,high school,free/reduced,none,54,72,59,61.666667
...,...,...,...,...,...,...,...,...,...
995,male,group B,high school,free/reduced,none,49,45,45,46.333333
996,female,group C,high school,standard,none,29,29,30,29.333333
997,male,group C,master's degree,free/reduced,completed,72,66,72,70.000000
998,male,group D,some high school,free/reduced,completed,80,79,79,79.333333
999,female,group D,some college,free/reduced,none,71,83,83,79.000000

In [35]:
# sort descending using index
df_exams.sort_values(by ='new_index',ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
new_index,,,,,,,,,
999,female,group D,some college,free/reduced,none,71,83,83,79.000000
998,male,group D,some high school,free/reduced,completed,80,79,79,79.333333
997,male,group C,master's degree,free/reduced,completed,72,66,72,70.000000
996,female,group C,high school,standard,none,29,29,30,29.333333
995,male,group B,high school,free/reduced,none,49,45,45,46.333333
...,...,...,...,...,...,...,...,...,...
4,male,group C,high school,free/reduced,none,54,72,59,61.666667
3,male,group E,high school,free/reduced,completed,57,56,54,55.666667
2,male,group D,high school,free/reduced,none,74,70,69,71.000000
1,female,group D,high school,standard,completed,56,68,74,66.000000
0,male,group E,some high school,free/reduced,completed,73,67,59,66.333333

# Rename columns and index with rename()

In [38]:
# rename column and overwrite values of the dataframe
df_exams = df_exams.rename(columns={'gender':'Gender'})

In [39]:
df_exams

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
new_index,,,,,,,,,
98,male,group E,associate's degree,free/reduced,completed,100,100,93,97.666667
403,female,group E,bachelor's degree,standard,none,100,100,100,100.000000
155,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000
273,female,group E,associate's degree,standard,none,100,100,100,100.000000
738,male,group D,some college,standard,completed,100,97,99,98.666667
...,...,...,...,...,...,...,...,...,...
701,female,group C,some college,free/reduced,none,22,39,33,31.333333
565,female,group B,some college,standard,none,19,38,32,29.666667
765,female,group B,some high school,free/reduced,none,18,32,28,26.000000
7,female,group B,high school,free/reduced,none,8,24,23,18.333333
502,female,group C,some high school,free/reduced,none,0,17,10,9.000000

In [42]:
# rename multiple columns and update the dataframe with inplace argument
df_exams.rename(columns={'math score':'MS',
                        'reading score':'RS',
                        'writing score':'Ws'},inplace=True)

In [43]:
df_exams

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,ms,rs,ws,average
new_index,,,,,,,,,
98,male,group E,associate's degree,free/reduced,completed,100,100,93,97.666667
403,female,group E,bachelor's degree,standard,none,100,100,100,100.000000
155,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000
273,female,group E,associate's degree,standard,none,100,100,100,100.000000
738,male,group D,some college,standard,completed,100,97,99,98.666667
...,...,...,...,...,...,...,...,...,...
701,female,group C,some college,free/reduced,none,22,39,33,31.333333
565,female,group B,some college,standard,none,19,38,32,29.666667
765,female,group B,some high school,free/reduced,none,18,32,28,26.000000
7,female,group B,high school,free/reduced,none,8,24,23,18.333333
502,female,group C,some high school,free/reduced,none,0,17,10,9.000000

# rename index

In [48]:
df_exams = pd.read_csv('StudentsPerformance.csv')

In [49]:
# rename index 0, 1 and 2 and update the dataframe
df_exams.rename(index={0:'A',1:'B',2:'C'},inplace=True)

In [51]:
df_exams.head(3)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
A,female,group B,bachelor's degree,standard,none,72,72,74
B,female,group C,some college,standard,completed,69,90,88
C,female,group B,master's degree,standard,none,90,95,93